// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cleanup() {
  return window['go']['vaults_storage']['AvatarStore']['Cleanup']();
}

export function Delete(arg1, arg2) {
  return window['go']['vaults_storage']['AvatarStore']['Delete'](arg1, arg2);
}

export function Exists(arg1, arg2) {
  return window['go']['vaults_storage']['AvatarStore']['Exists'](arg1, arg2);
}

export function Load(arg1, arg2) {
  return window['go']['vaults_storage']['AvatarStore']['Load'](arg1, arg2);
}

export function LoadBase64(arg1) {
  return window['go']['vaults_storage']['AvatarStore']['LoadBase64'](arg1);
}

export function Save(arg1, arg2) {
  return window['go']['vaults_storage']['AvatarStore']['Save'](arg1, arg2);
}
