// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cleanup():Promise<void>;

export function Delete(arg1:string,arg2:string):Promise<void>;

export function Exists(arg1:string,arg2:string):Promise<boolean>;

export function Load(arg1:string,arg2:string):Promise<Array<number>>;

export function LoadBase64(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Save(arg1:string,arg2:Array<number>):Promise<string>;
