// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptChannelInvitation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AcceptChannelInvitation'](arg1, arg2, arg3, arg4);
}

export function AcceptShare(arg1, arg2, arg3) {
  return window['go']['main']['App']['AcceptShare'](arg1, arg2, arg3);
}

export function AccessDecryptVaultEntry(arg1, arg2) {
  return window['go']['main']['App']['AccessDecryptVaultEntry'](arg1, arg2);
}

export function ActivateChannel(arg1, arg2) {
  return window['go']['main']['App']['ActivateChannel'](arg1, arg2);
}

export function AddAttachements(arg1, arg2) {
  return window['go']['main']['App']['AddAttachements'](arg1, arg2);
}

export function AddEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddEntry'](arg1, arg2, arg3);
}

export function AddParticipant(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddParticipant'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AddReceiver(arg1, arg2) {
  return window['go']['main']['App']['AddReceiver'](arg1, arg2);
}

export function AddRecipient(arg1, arg2) {
  return window['go']['main']['App']['AddRecipient'](arg1, arg2);
}

export function AppendThreadEvent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AppendThreadEvent'](arg1, arg2, arg3, arg4);
}

export function Archive(arg1, arg2) {
  return window['go']['main']['App']['Archive'](arg1, arg2);
}

export function CancelSubscription(arg1, arg2) {
  return window['go']['main']['App']['CancelSubscription'](arg1, arg2);
}

export function CheckEmail(arg1) {
  return window['go']['main']['App']['CheckEmail'](arg1);
}

export function CheckPaymentOnResume() {
  return window['go']['main']['App']['CheckPaymentOnResume']();
}

export function CheckSession(arg1) {
  return window['go']['main']['App']['CheckSession'](arg1);
}

export function CheckStellarKeyForVault(arg1) {
  return window['go']['main']['App']['CheckStellarKeyForVault'](arg1);
}

export function CheckUserEmail(arg1, arg2) {
  return window['go']['main']['App']['CheckUserEmail'](arg1, arg2);
}

export function CompleteOnboarding() {
  return window['go']['main']['App']['CompleteOnboarding']();
}

export function ConnectToRealtime(arg1) {
  return window['go']['main']['App']['ConnectToRealtime'](arg1);
}

export function ConnectVault(arg1, arg2) {
  return window['go']['main']['App']['ConnectVault'](arg1, arg2);
}

export function ConnectWithStellar(arg1) {
  return window['go']['main']['App']['ConnectWithStellar'](arg1);
}

export function CountUnread(arg1) {
  return window['go']['main']['App']['CountUnread'](arg1);
}

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function CreateChannel(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['CreateChannel'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function CreateCollaborativeShare(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateCollaborativeShare'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateLinkShare(arg1, arg2) {
  return window['go']['main']['App']['CreateLinkShare'](arg1, arg2);
}

export function CreateShare(arg1) {
  return window['go']['main']['App']['CreateShare'](arg1);
}

export function CreateThread(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateThread'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateWorkspace(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2, arg3, arg4);
}

export function DecryptAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptAttachment'](arg1, arg2, arg3);
}

export function DeleteChannel(arg1, arg2) {
  return window['go']['main']['App']['DeleteChannel'](arg1, arg2);
}

export function DeleteEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteEntry'](arg1, arg2, arg3);
}

export function DeleteFolder(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolder'](arg1, arg2);
}

export function DownloadAttachment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadAttachment'](arg1, arg2, arg3, arg4);
}

export function DownloadReceipt(arg1, arg2) {
  return window['go']['main']['App']['DownloadReceipt'](arg1, arg2);
}

export function DownloadShareAttachement(arg1, arg2) {
  return window['go']['main']['App']['DownloadShareAttachement'](arg1, arg2);
}

export function DummyExposeEntries(arg1) {
  return window['go']['main']['App']['DummyExposeEntries'](arg1);
}

export function EditConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditConfig'](arg1, arg2, arg3);
}

export function EditEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditEntry'](arg1, arg2, arg3);
}

export function EditUserInfos(arg1, arg2) {
  return window['go']['main']['App']['EditUserInfos'](arg1, arg2);
}

export function EncryptAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['EncryptAttachment'](arg1, arg2, arg3);
}

export function FetchUsers() {
  return window['go']['main']['App']['FetchUsers']();
}

export function FlushAllSessions() {
  return window['go']['main']['App']['FlushAllSessions']();
}

export function GenerateApiKey(arg1) {
  return window['go']['main']['App']['GenerateApiKey'](arg1);
}

export function GetAllConfigs(arg1, arg2) {
  return window['go']['main']['App']['GetAllConfigs'](arg1, arg2);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetBillingHistory(arg1, arg2) {
  return window['go']['main']['App']['GetBillingHistory'](arg1, arg2);
}

export function GetChannel(arg1, arg2) {
  return window['go']['main']['App']['GetChannel'](arg1, arg2);
}

export function GetCheckoutURL(arg1) {
  return window['go']['main']['App']['GetCheckoutURL'](arg1);
}

export function GetConfig(arg1, arg2) {
  return window['go']['main']['App']['GetConfig'](arg1, arg2);
}

export function GetFoldersByVault(arg1, arg2) {
  return window['go']['main']['App']['GetFoldersByVault'](arg1, arg2);
}

export function GetIPFSFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetIPFSFile'](arg1, arg2, arg3, arg4);
}

export function GetPacks(arg1) {
  return window['go']['main']['App']['GetPacks'](arg1);
}

export function GetPendingPaymentRequests(arg1) {
  return window['go']['main']['App']['GetPendingPaymentRequests'](arg1);
}

export function GetRecommendedTier(arg1) {
  return window['go']['main']['App']['GetRecommendedTier'](arg1);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetShareForAccept(arg1, arg2) {
  return window['go']['main']['App']['GetShareForAccept'](arg1, arg2);
}

export function GetStorageUsage(arg1, arg2) {
  return window['go']['main']['App']['GetStorageUsage'](arg1, arg2);
}

export function GetSubscriptionDetails(arg1) {
  return window['go']['main']['App']['GetSubscriptionDetails'](arg1);
}

export function GetSubscriptionFromCloud(arg1, arg2) {
  return window['go']['main']['App']['GetSubscriptionFromCloud'](arg1, arg2);
}

export function GetTemplate(arg1) {
  return window['go']['main']['App']['GetTemplate'](arg1);
}

export function GetTierFeatures() {
  return window['go']['main']['App']['GetTierFeatures']();
}

export function GetUserVaultKey(arg1) {
  return window['go']['main']['App']['GetUserVaultKey'](arg1);
}

export function GetVault(arg1) {
  return window['go']['main']['App']['GetVault'](arg1);
}

export function GetVaultAvatar(arg1, arg2) {
  return window['go']['main']['App']['GetVaultAvatar'](arg1, arg2);
}

export function GetVaultFromCloud(arg1, arg2) {
  return window['go']['main']['App']['GetVaultFromCloud'](arg1, arg2);
}

export function ImportVaultWithKey(arg1) {
  return window['go']['main']['App']['ImportVaultWithKey'](arg1);
}

export function InviteToChannel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InviteToChannel'](arg1, arg2, arg3, arg4);
}

export function IsVaultDirty(arg1) {
  return window['go']['main']['App']['IsVaultDirty'](arg1);
}

export function ListByUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListByUser'](arg1, arg2, arg3);
}

export function ListChannels(arg1, arg2) {
  return window['go']['main']['App']['ListChannels'](arg1, arg2);
}

export function ListLinkSharesByMe(arg1) {
  return window['go']['main']['App']['ListLinkSharesByMe'](arg1);
}

export function ListLinkSharesWithMe(arg1) {
  return window['go']['main']['App']['ListLinkSharesWithMe'](arg1);
}

export function ListParticipants(arg1, arg2) {
  return window['go']['main']['App']['ListParticipants'](arg1, arg2);
}

export function ListPendingIntentSharesByMe(arg1) {
  return window['go']['main']['App']['ListPendingIntentSharesByMe'](arg1);
}

export function ListPendingIntentSharesWithMe(arg1) {
  return window['go']['main']['App']['ListPendingIntentSharesWithMe'](arg1);
}

export function ListReceivedShares(arg1) {
  return window['go']['main']['App']['ListReceivedShares'](arg1);
}

export function ListSharedEntries(arg1) {
  return window['go']['main']['App']['ListSharedEntries'](arg1);
}

export function ListThreadEvents(arg1, arg2) {
  return window['go']['main']['App']['ListThreadEvents'](arg1, arg2);
}

export function ListThreads(arg1, arg2) {
  return window['go']['main']['App']['ListThreads'](arg1, arg2);
}

export function ListWorkspaces(arg1, arg2) {
  return window['go']['main']['App']['ListWorkspaces'](arg1, arg2);
}

export function LoadAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoadAttachment'](arg1, arg2, arg3);
}

export function LoadAvatar(arg1, arg2) {
  return window['go']['main']['App']['LoadAvatar'](arg1, arg2);
}

export function MarkAllRead(arg1) {
  return window['go']['main']['App']['MarkAllRead'](arg1);
}

export function MarkRead(arg1, arg2) {
  return window['go']['main']['App']['MarkRead'](arg1, arg2);
}

export function NotifyPaymentSuccess(arg1) {
  return window['go']['main']['App']['NotifyPaymentSuccess'](arg1);
}

export function OnPaymentConfirmation(arg1, arg2, arg3) {
  return window['go']['main']['App']['OnPaymentConfirmation'](arg1, arg2, arg3);
}

export function OpenFileInDefaultApp(arg1) {
  return window['go']['main']['App']['OpenFileInDefaultApp'](arg1);
}

export function OpenGoogle() {
  return window['go']['main']['App']['OpenGoogle']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PollPaymentStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['PollPaymentStatus'](arg1, arg2, arg3);
}

export function ProcessEncryptedPayment(arg1) {
  return window['go']['main']['App']['ProcessEncryptedPayment'](arg1);
}

export function ReactivateSubscription(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReactivateSubscription'](arg1, arg2, arg3);
}

export function RecoverVaultWithKey(arg1) {
  return window['go']['main']['App']['RecoverVaultWithKey'](arg1);
}

export function RefreshToken(arg1) {
  return window['go']['main']['App']['RefreshToken'](arg1);
}

export function RejectShare(arg1, arg2, arg3) {
  return window['go']['main']['App']['RejectShare'](arg1, arg2, arg3);
}

export function RequireAuth(arg1) {
  return window['go']['main']['App']['RequireAuth'](arg1);
}

export function RestoreCloudTokenForUser(arg1) {
  return window['go']['main']['App']['RestoreCloudTokenForUser'](arg1);
}

export function RestoreEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreEntry'](arg1, arg2, arg3);
}

export function RevokeChannel(arg1, arg2) {
  return window['go']['main']['App']['RevokeChannel'](arg1, arg2);
}

export function RevokeRecipient(arg1, arg2) {
  return window['go']['main']['App']['RevokeRecipient'](arg1, arg2);
}

export function RevokeShare(arg1, arg2) {
  return window['go']['main']['App']['RevokeShare'](arg1, arg2);
}

export function SaveSessionTest(arg1) {
  return window['go']['main']['App']['SaveSessionTest'](arg1);
}

export function SetStorageMode(arg1, arg2) {
  return window['go']['main']['App']['SetStorageMode'](arg1, arg2);
}

export function SetupFreeAndActivate(arg1) {
  return window['go']['main']['App']['SetupFreeAndActivate'](arg1);
}

export function SetupPaymentAndActivate(arg1) {
  return window['go']['main']['App']['SetupPaymentAndActivate'](arg1);
}

export function SignIn(arg1) {
  return window['go']['main']['App']['SignIn'](arg1);
}

export function SignInWithIdentity(arg1) {
  return window['go']['main']['App']['SignInWithIdentity'](arg1);
}

export function SignInWithStellar(arg1) {
  return window['go']['main']['App']['SignInWithStellar'](arg1);
}

export function SignOut(arg1) {
  return window['go']['main']['App']['SignOut'](arg1);
}

export function SimulatePackWorker(arg1, arg2) {
  return window['go']['main']['App']['SimulatePackWorker'](arg1, arg2);
}

export function SynchronizeVault(arg1, arg2) {
  return window['go']['main']['App']['SynchronizeVault'](arg1, arg2);
}

export function TrashEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['TrashEntry'](arg1, arg2, arg3);
}

export function UpdateAttachment(arg1, arg2) {
  return window['go']['main']['App']['UpdateAttachment'](arg1, arg2);
}

export function UpdateChannel(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateChannel'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateFolder(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateFolder'](arg1, arg2, arg3, arg4);
}

export function UpdatePaymentMethod(arg1, arg2) {
  return window['go']['main']['App']['UpdatePaymentMethod'](arg1, arg2);
}

export function UpdateRecipient(arg1, arg2) {
  return window['go']['main']['App']['UpdateRecipient'](arg1, arg2);
}

export function UpgradeSubscription(arg1, arg2) {
  return window['go']['main']['App']['UpgradeSubscription'](arg1, arg2);
}

export function UploadAttachmentToIPFS(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadAttachmentToIPFS'](arg1, arg2, arg3);
}

export function UploadAttachmentToIPFSWithEncryption(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadAttachmentToIPFSWithEncryption'](arg1, arg2, arg3);
}

export function UploadAttachments(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UploadAttachments'](arg1, arg2, arg3, arg4, arg5);
}

export function UploadAvatar(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadAvatar'](arg1, arg2, arg3);
}

export function UploadToIPFS(arg1, arg2) {
  return window['go']['main']['App']['UploadToIPFS'](arg1, arg2);
}
