// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';
import {share_application_use_cases} from '../models';
import {blockchain} from '../models';
import {handlers} from '../models';
import {auth} from '../models';
import {main} from '../models';
import {onboarding_usecase} from '../models';
import {onboarding_ui_wails} from '../models';
import {vaults_domain} from '../models';
import {share_application_dto} from '../models';
import {share_domain} from '../models';
import {tracecore} from '../models';
import {models} from '../models';
import {identity_dtos} from '../models';
import {identity_domain} from '../models';
import {billing_domain} from '../models';
import {onboarding_domain} from '../models';
import {stellar_recovery_domain} from '../models';
import {subscription_domain} from '../models';
import {vault_dto} from '../models';

export function AddEntry(arg1:string,arg2:json.RawMessage,arg3:string):Promise<any>;

export function AddReceiver(arg1:string,arg2:share_application_use_cases.AddReceiverInput):Promise<share_application_use_cases.AddReceiverResult>;

export function AuthVerify(arg1:blockchain.SignatureVerification):Promise<string>;

export function CancelSubscription(arg1:string,arg2:string):Promise<void>;

export function CheckEmail(arg1:string):Promise<handlers.CheckEmailResponse>;

export function CheckPaymentOnResume():Promise<void>;

export function CheckSession(arg1:string):Promise<auth.TokenPairs>;

export function CheckStellarKeyForVault(arg1:string):Promise<main.CheckKeyResponse>;

export function ConnectWithStellar(arg1:handlers.LoginRequest):Promise<main.CheckKeyResponse>;

export function CreateAccount(arg1:onboarding_usecase.AccountCreationRequest):Promise<onboarding_ui_wails.AccountCreationResponse>;

export function CreateFolder(arg1:string,arg2:string):Promise<vaults_domain.VaultPayload>;

export function CreateLinkShare(arg1:share_application_dto.LinkShareCreateRequest,arg2:string):Promise<main.CreateLinkShareOutput>;

export function CreateShare(arg1:main.CreateShareInput):Promise<share_domain.ShareEntry>;

export function CreateStellarCommit(arg1:string,arg2:string):Promise<string>;

export function DecryptVaultEntry(arg1:string,arg2:tracecore.AccessCryptoShareRequest):Promise<tracecore.CloudResponse_vault_app_internal_tracecore_DecryptCryptoShareResponse_>;

export function DeleteEntry(arg1:string,arg2:json.RawMessage,arg3:string):Promise<any>;

export function DeleteFolder(arg1:string,arg2:string):Promise<string>;

export function DownloadReceipt(arg1:string,arg2:string):Promise<main.Receipt>;

export function DummyExposeEntries(arg1:models.Entries):Promise<models.Entries>;

export function EditEntry(arg1:string,arg2:json.RawMessage,arg3:string):Promise<any>;

export function EditUserInfos(arg1:string,arg2:identity_dtos.EditUserInfosRequest):Promise<void>;

export function EncryptFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function EncryptVault(arg1:string,arg2:string):Promise<string>;

export function FetchUsers():Promise<Array<models.UserDTO>>;

export function FlushAllSessions():Promise<void>;

export function GenerateApiKey(arg1:main.GenerateApiKeyInput):Promise<main.GenerateApiKeyOutput>;

export function GetBillingHistory(arg1:string,arg2:number):Promise<Array<main.PaymentHistory>>;

export function GetCheckoutURL(arg1:identity_domain.IdentityChoice,arg2:boolean,arg3:string,arg4:string,arg5:string,arg6:string):Promise<main.CreateCheckoutResponse>;

export function GetFoldersByVault(arg1:string,arg2:string):Promise<Array<vaults_domain.Folder>>;

export function GetPendingPaymentRequests(arg1:string):Promise<Array<billing_domain.PaymentRequest>>;

export function GetRecommendedTier(arg1:identity_domain.IdentityChoice):Promise<main.OnboardingStep1Response>;

export function GetSession(arg1:string):Promise<main.GetSessionResponse>;

export function GetShareForAccept(arg1:string,arg2:string):Promise<share_domain.ShareAcceptData>;

export function GetStorageUsage(arg1:string):Promise<main.StorageUsage>;

export function GetSubscriptionDetails(arg1:string):Promise<main.Subscription>;

export function GetTierFeatures():Promise<Record<string, onboarding_domain.SubscriptionFeatures>>;

export function GetUserVaultKey(arg1:string):Promise<string>;

export function GetVault(arg1:string):Promise<Record<string, any>>;

export function ImportVaultWithKey(arg1:string):Promise<stellar_recovery_domain.ImportedKey>;

export function IsVaultDirty(arg1:string):Promise<boolean>;

export function ListLinkSharesByMe(arg1:string):Promise<main.ListLinkSharesByMeResponse>;

export function ListLinkSharesWithMe(arg1:string):Promise<any>;

export function ListReceivedShares(arg1:string):Promise<any>;

export function ListSharedEntries(arg1:string):Promise<any>;

export function NotifyPaymentSuccess(arg1:string):Promise<void>;

export function OnPaymentConfirmation(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenGoogle():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PollPaymentStatus(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ProcessEncryptedPayment(arg1:main.ClientPaymentRequest):Promise<void>;

export function ReactivateSubscription(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RecoverVaultWithKey(arg1:string):Promise<stellar_recovery_domain.RecoveredVault>;

export function RefreshToken(arg1:string):Promise<auth.TokenPairs>;

export function RejectShare(arg1:string,arg2:string):Promise<share_application_use_cases.RejectShareResult>;

export function RequestChallenge(arg1:blockchain.ChallengeRequest):Promise<blockchain.ChallengeResponse>;

export function RequireAuth(arg1:string):Promise<auth.Claims>;

export function RestoreEntry(arg1:string,arg2:json.RawMessage,arg3:string):Promise<any>;

export function SaveSessionTest(arg1:string):Promise<void>;

export function SetupPaymentAndActivate(arg1:onboarding_usecase.PaymentSetupRequest):Promise<subscription_domain.Subscription>;

export function Sign(arg1:handlers.LoginRequest):Promise<handlers.LoginResponse>;

export function SignInWithIdentity(arg1:handlers.LoginRequest):Promise<vault_dto.LoginResponse>;

export function SignInWithStellar(arg1:handlers.LoginRequest):Promise<vault_dto.LoginResponse>;

export function SignOut(arg1:string):Promise<void>;

export function SignUp(arg1:handlers.OnBoarding):Promise<handlers.OnBoardingResponse>;

export function SynchronizeVault(arg1:string,arg2:string):Promise<string>;

export function TrashEntry(arg1:string,arg2:json.RawMessage,arg3:string):Promise<any>;

export function UpdateFolder(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<vaults_domain.Folder>;

export function UpdatePaymentMethod(arg1:string,arg2:main.UpdatePaymentMethodRequest):Promise<void>;

export function UpgradeSubscription(arg1:string,arg2:main.UpgradeRequest):Promise<void>;

export function UploadToIPFS(arg1:string,arg2:string):Promise<string>;
