// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';
import {share_application_use_cases} from '../models';
import {blockchain} from '../models';
import {handlers} from '../models';
import {main} from '../models';
import {models} from '../models';
import {share_domain} from '../models';
import {stellar_recovery_domain} from '../models';

export function AddEntry(arg1:string,arg2:json.RawMessage,arg3:string):Promise<any>;

export function AddReceiver(arg1:string,arg2:share_application_use_cases.AddReceiverInput):Promise<share_application_use_cases.AddReceiverResult>;

export function AuthVerify(arg1:blockchain.SignatureVerification):Promise<string>;

export function CheckEmail(arg1:string):Promise<handlers.CheckEmailResponse>;

export function CheckSession(arg1:number):Promise<string>;

export function CheckStellarKeyForVault(arg1:string):Promise<main.CheckKeyResponse>;

export function ConnectWithStellar(arg1:handlers.LoginRequest):Promise<main.CheckKeyResponse>;

export function CreateFolder(arg1:string,arg2:string):Promise<models.VaultPayload>;

export function CreateShare(arg1:main.CreateShareInput):Promise<share_domain.ShareEntry>;

export function CreateStellarCommit(arg1:string,arg2:string):Promise<string>;

export function DeleteFolder(arg1:number,arg2:number,arg3:string):Promise<string>;

export function DummyExposeEntries(arg1:models.Entries):Promise<models.Entries>;

export function EditEntry(arg1:string,arg2:json.RawMessage,arg3:string):Promise<any>;

export function EncryptFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function EncryptVault(arg1:string,arg2:string):Promise<string>;

export function FetchUsers():Promise<Array<models.UserDTO>>;

export function FlushAllSessions():Promise<void>;

export function GetFoldersByVault(arg1:string,arg2:string):Promise<Array<models.Folder>>;

export function GetShareForAccept(arg1:string,arg2:string):Promise<share_domain.ShareAcceptData>;

export function ImportVaultWithKey(arg1:string):Promise<stellar_recovery_domain.ImportedKey>;

export function IsVaultDirty(arg1:string):Promise<boolean>;

export function ListReceivedShares(arg1:string):Promise<any>;

export function ListSharedEntries(arg1:string):Promise<any>;

export function RecoverVaultWithKey(arg1:string):Promise<stellar_recovery_domain.RecoveredVault>;

export function RefreshToken(arg1:number):Promise<string>;

export function RejectShare(arg1:string,arg2:number):Promise<share_application_use_cases.RejectShareResult>;

export function RequestChallenge(arg1:blockchain.ChallengeRequest):Promise<blockchain.ChallengeResponse>;

export function RestoreEntry(arg1:string,arg2:json.RawMessage,arg3:string):Promise<any>;

export function SignIn(arg1:handlers.LoginRequest):Promise<handlers.LoginResponse>;

export function SignInWithStellar(arg1:handlers.LoginRequest):Promise<handlers.LoginResponse>;

export function SignOut(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SignUp(arg1:handlers.OnBoarding):Promise<handlers.OnBoardingResponse>;

export function SynchronizeVault(arg1:string,arg2:string):Promise<string>;

export function TrashEntry(arg1:string,arg2:json.RawMessage,arg3:string):Promise<any>;

export function UpdateFolder(arg1:number,arg2:string,arg3:boolean,arg4:string):Promise<models.Folder>;

export function UploadToIPFS(arg1:string,arg2:string):Promise<string>;
