// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tracecore_types} from '../models';
import {vault_dto} from '../models';
import {vaults_domain} from '../models';
import {json} from '../models';
import {share_entry_use_cases} from '../models';
import {main} from '../models';
import {auth} from '../models';
import {identity_domain} from '../models';
import {handlers} from '../models';
import {onboarding_usecase} from '../models';
import {onboarding_ui_wails} from '../models';
import {share_entry_application_dto} from '../models';
import {share_entry_domain} from '../models';
import {models} from '../models';
import {app_config_dto} from '../models';
import {identity_dtos} from '../models';
import {subscription_domain} from '../models';
import {onboarding_domain} from '../models';
import {app_config_domain} from '../models';
import {app_config_worker} from '../models';
import {billing_domain} from '../models';
import {stellar_recovery_domain} from '../models';
import {notification_center_domain} from '../models';
import {tracecore} from '../models';

export function AcceptShare(arg1:string,arg2:string,arg3:string):Promise<tracecore_types.CloudResponse_vault_app_internal_tracecore_types_PendingShareIntent_>;

export function AccessDecryptVaultEntry(arg1:string,arg2:tracecore_types.AccessCryptoShareRequest):Promise<tracecore_types.CloudResponse_vault_app_internal_tracecore_types_DecryptCryptoShareResponse_>;

export function AddAttachements(arg1:string,arg2:vault_dto.AddAttachementsRequest):Promise<Array<vaults_domain.Attachment>>;

export function AddEntry(arg1:string,arg2:json.RawMessage,arg3:string):Promise<any>;

export function AddReceiver(arg1:string,arg2:share_entry_use_cases.AddReceiverInput):Promise<share_entry_use_cases.AddReceiverResult>;

export function AddRecipient(arg1:string,arg2:json.RawMessage):Promise<tracecore_types.CloudResponse_vault_app_internal_tracecore_CloudCryptographicShare_>;

export function AppendThreadEvent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<tracecore_types.ThreadEventDTO>;

export function Archive(arg1:string,arg2:string):Promise<void>;

export function CancelSubscription(arg1:string,arg2:string):Promise<void>;

export function CheckEmail(arg1:string):Promise<main.CheckEmailResponse>;

export function CheckPaymentOnResume():Promise<void>;

export function CheckSession(arg1:string):Promise<auth.TokenPairs>;

export function CheckStellarKeyForVault(arg1:string):Promise<main.CheckKeyResponse>;

export function CheckUserEmail(arg1:string,arg2:string):Promise<tracecore_types.User>;

export function CompleteOnboarding():Promise<void>;

export function ConnectToRealtime(arg1:identity_domain.User):Promise<void>;

export function ConnectWithStellar(arg1:handlers.LoginRequest):Promise<main.CheckKeyResponse>;

export function CountUnread(arg1:string):Promise<number>;

export function CreateAccount(arg1:onboarding_usecase.AccountCreationRequest):Promise<onboarding_ui_wails.AccountCreationResponse>;

export function CreateChannel(arg1:string,arg2:string,arg3:string,arg4:string):Promise<tracecore_types.ChannelDTO>;

export function CreateCollaborativeShare(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<tracecore_types.ShareEntryRefDTO>;

export function CreateFolder(arg1:string,arg2:string):Promise<vaults_domain.VaultPayload>;

export function CreateLinkShare(arg1:share_entry_application_dto.LinkShareCreateRequest,arg2:string):Promise<main.CreateLinkShareOutput>;

export function CreateShare(arg1:main.CreateShareInput):Promise<share_entry_domain.ShareEntry>;

export function CreateThread(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<tracecore_types.ThreadDTO>;

export function CreateWorkspace(arg1:string,arg2:string,arg3:string,arg4:string):Promise<tracecore_types.Workspace>;

export function DecryptAttachment(arg1:string,arg2:Array<number>,arg3:string):Promise<Array<number>>;

export function DeleteEntry(arg1:string,arg2:json.RawMessage,arg3:string):Promise<any>;

export function DeleteFolder(arg1:string,arg2:string):Promise<string>;

export function DownloadAttachment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function DownloadReceipt(arg1:string,arg2:string):Promise<main.Receipt>;

export function DownloadShareAttachement(arg1:vault_dto.DownloadShareAttachmentRequest,arg2:string):Promise<string>;

export function DummyExposeEntries(arg1:models.Entries):Promise<models.Entries>;

export function EditConfig(arg1:string,arg2:app_config_dto.Settings,arg3:string):Promise<void>;

export function EditEntry(arg1:string,arg2:json.RawMessage,arg3:string):Promise<any>;

export function EditUserInfos(arg1:string,arg2:identity_dtos.EditUserInfosRequest):Promise<void>;

export function EncryptAttachment(arg1:string,arg2:Array<number>,arg3:string):Promise<Array<number>>;

export function FetchUsers():Promise<Array<models.UserDTO>>;

export function FlushAllSessions():Promise<void>;

export function GenerateApiKey(arg1:main.GenerateApiKeyInput):Promise<main.GenerateApiKeyOutput>;

export function GetAllConfigs(arg1:string,arg2:string):Promise<subscription_domain.Subscription>;

export function GetAppState():Promise<onboarding_domain.AppState>;

export function GetBillingHistory(arg1:string,arg2:number):Promise<tracecore_types.CloudResponse___vault_app_internal_tracecore_types_PaymentHistory_>;

export function GetCheckoutURL(arg1:main.CheckoutContext):Promise<main.CreateCheckoutResponse>;

export function GetConfig(arg1:string,arg2:string):Promise<app_config_domain.Config>;

export function GetFoldersByVault(arg1:string,arg2:string):Promise<Array<vaults_domain.Folder>>;

export function GetIPFSFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetPacks(arg1:string):Promise<app_config_worker.PackDTO>;

export function GetPendingPaymentRequests(arg1:string):Promise<Array<billing_domain.PaymentRequest>>;

export function GetRecommendedTier(arg1:identity_domain.IdentityChoice):Promise<main.OnboardingStep1Response>;

export function GetSession(arg1:string):Promise<main.GetSessionResponse>;

export function GetShareForAccept(arg1:string,arg2:string):Promise<share_entry_domain.ShareAcceptData>;

export function GetStorageUsage(arg1:string,arg2:subscription_domain.SubscriptionTier):Promise<tracecore_types.CloudResponse_vault_app_internal_tracecore_types_StorageUsageResponse_>;

export function GetSubscriptionDetails(arg1:string):Promise<main.Subscription>;

export function GetSubscriptionFromCloud(arg1:string,arg2:string):Promise<subscription_domain.Subscription>;

export function GetTemplate(arg1:string):Promise<app_config_worker.TemplateDTO>;

export function GetTierFeatures():Promise<Record<string, onboarding_domain.SubscriptionFeatures>>;

export function GetUserVaultKey(arg1:string):Promise<string>;

export function GetVault(arg1:string):Promise<Record<string, any>>;

export function GetVaultAvatar(arg1:string,arg2:string):Promise<string>;

export function GetVaultFromCloud(arg1:string,arg2:string):Promise<tracecore_types.Vault>;

export function ImportVaultWithKey(arg1:string):Promise<stellar_recovery_domain.ImportedKey>;

export function IsVaultDirty(arg1:string):Promise<boolean>;

export function ListByUser(arg1:string,arg2:number,arg3:number):Promise<Array<notification_center_domain.Notification>>;

export function ListChannels(arg1:string,arg2:string):Promise<Array<tracecore_types.ChannelDTO>>;

export function ListLinkSharesByMe(arg1:string):Promise<main.ListLinkSharesByMeResponse>;

export function ListLinkSharesWithMe(arg1:string):Promise<any>;

export function ListPendingIntentSharesByMe(arg1:string):Promise<tracecore_types.CloudResponse___vault_app_internal_tracecore_types_PendingShareIntent_>;

export function ListPendingIntentSharesWithMe(arg1:string):Promise<tracecore_types.CloudResponse___vault_app_internal_tracecore_types_PendingShareIntent_>;

export function ListReceivedShares(arg1:string):Promise<any>;

export function ListSharedEntries(arg1:string):Promise<any>;

export function ListThreadEvents(arg1:string,arg2:string):Promise<Array<tracecore_types.ThreadEventDTO>>;

export function ListThreads(arg1:string,arg2:string):Promise<Array<tracecore_types.ThreadDTO>>;

export function ListWorkspaces(arg1:string,arg2:string):Promise<Array<tracecore_types.Workspace>>;

export function LoadAttachment(arg1:string,arg2:string,arg3:string):Promise<string>;

export function LoadAvatar(arg1:string,arg2:string):Promise<string>;

export function MarkAllRead(arg1:string):Promise<void>;

export function MarkRead(arg1:string,arg2:string):Promise<void>;

export function NotifyPaymentSuccess(arg1:string):Promise<void>;

export function OnPaymentConfirmation(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenFileInDefaultApp(arg1:string):Promise<void>;

export function OpenGoogle():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PollPaymentStatus(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ProcessEncryptedPayment(arg1:main.ClientPaymentRequest):Promise<void>;

export function ReactivateSubscription(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RecoverVaultWithKey(arg1:string):Promise<stellar_recovery_domain.RecoveredVault>;

export function RefreshToken(arg1:string):Promise<auth.TokenPairs>;

export function RejectShare(arg1:string,arg2:string,arg3:string):Promise<tracecore_types.CloudResponse_vault_app_internal_tracecore_types_PendingShareIntent_>;

export function RequireAuth(arg1:string):Promise<auth.Claims>;

export function RestoreEntry(arg1:string,arg2:json.RawMessage,arg3:string):Promise<any>;

export function RevokeRecipient(arg1:string,arg2:json.RawMessage):Promise<tracecore_types.CloudResponse_vault_app_internal_tracecore_CloudCryptographicShare_>;

export function RevokeShare(arg1:string,arg2:json.RawMessage):Promise<tracecore_types.CloudResponse_vault_app_internal_tracecore_CloudCryptographicShare_>;

export function SaveSessionTest(arg1:string):Promise<void>;

export function SetStorageMode(arg1:string,arg2:string):Promise<void>;

export function SetupFreeAndActivate(arg1:onboarding_usecase.FreeSetupRequest):Promise<tracecore.FreeCheckoutResponse>;

export function SetupPaymentAndActivate(arg1:onboarding_usecase.PaymentSetupRequest):Promise<subscription_domain.Subscription>;

export function SignIn(arg1:handlers.LoginRequest):Promise<vault_dto.LoginResponse>;

export function SignInWithIdentity(arg1:handlers.LoginRequest):Promise<vault_dto.LoginResponse>;

export function SignInWithStellar(arg1:handlers.LoginRequest):Promise<vault_dto.LoginResponse>;

export function SignOut(arg1:string):Promise<void>;

export function SimulatePackWorker(arg1:string,arg2:string):Promise<void>;

export function SynchronizeVault(arg1:string,arg2:string):Promise<string>;

export function TrashEntry(arg1:string,arg2:json.RawMessage,arg3:string):Promise<any>;

export function UpdateAttachment(arg1:string,arg2:vaults_domain.Attachment):Promise<vaults_domain.Attachment>;

export function UpdateFolder(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<vaults_domain.Folder>;

export function UpdatePaymentMethod(arg1:string,arg2:main.UpdatePaymentMethodRequest):Promise<void>;

export function UpdateRecipient(arg1:string,arg2:json.RawMessage):Promise<tracecore_types.CloudResponse_vault_app_internal_tracecore_CloudCryptographicShare_>;

export function UpgradeSubscription(arg1:string,arg2:main.UpgradeRequest):Promise<void>;

export function UploadAttachmentToIPFS(arg1:string,arg2:Array<number>,arg3:string):Promise<string>;

export function UploadAttachmentToIPFSWithEncryption(arg1:string,arg2:Array<number>,arg3:string):Promise<string>;

export function UploadAttachments(arg1:string,arg2:string,arg3:string,arg4:json.RawMessage,arg5:vault_dto.SelectedAttachments):Promise<vaults_domain.VaultEntry>;

export function UploadAvatar(arg1:string,arg2:string,arg3:Array<number>):Promise<string>;

export function UploadToIPFS(arg1:string,arg2:string):Promise<string>;
