// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddEntry'](arg1, arg2, arg3);
}

export function AddReceiver(arg1, arg2) {
  return window['go']['main']['App']['AddReceiver'](arg1, arg2);
}

export function AuthVerify(arg1) {
  return window['go']['main']['App']['AuthVerify'](arg1);
}

export function CheckEmail(arg1) {
  return window['go']['main']['App']['CheckEmail'](arg1);
}

export function CheckSession(arg1) {
  return window['go']['main']['App']['CheckSession'](arg1);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateShare(arg1) {
  return window['go']['main']['App']['CreateShare'](arg1);
}

export function CreateStellarCommit(arg1, arg2) {
  return window['go']['main']['App']['CreateStellarCommit'](arg1, arg2);
}

export function DeleteFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteFolder'](arg1, arg2, arg3);
}

export function DummyExposeEntries(arg1) {
  return window['go']['main']['App']['DummyExposeEntries'](arg1);
}

export function EditEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditEntry'](arg1, arg2, arg3);
}

export function EncryptFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['EncryptFile'](arg1, arg2, arg3);
}

export function EncryptVault(arg1, arg2) {
  return window['go']['main']['App']['EncryptVault'](arg1, arg2);
}

export function FetchUsers() {
  return window['go']['main']['App']['FetchUsers']();
}

export function FlushAllSessions() {
  return window['go']['main']['App']['FlushAllSessions']();
}

export function GetFoldersByVault(arg1, arg2) {
  return window['go']['main']['App']['GetFoldersByVault'](arg1, arg2);
}

export function GetShareForAccept(arg1, arg2) {
  return window['go']['main']['App']['GetShareForAccept'](arg1, arg2);
}

export function IsVaultDirty(arg1) {
  return window['go']['main']['App']['IsVaultDirty'](arg1);
}

export function ListReceivedShares(arg1) {
  return window['go']['main']['App']['ListReceivedShares'](arg1);
}

export function ListSharedEntries(arg1) {
  return window['go']['main']['App']['ListSharedEntries'](arg1);
}

export function RefreshToken(arg1) {
  return window['go']['main']['App']['RefreshToken'](arg1);
}

export function RejectShare(arg1, arg2) {
  return window['go']['main']['App']['RejectShare'](arg1, arg2);
}

export function RequestChallenge(arg1) {
  return window['go']['main']['App']['RequestChallenge'](arg1);
}

export function RestoreEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreEntry'](arg1, arg2, arg3);
}

export function SignIn(arg1) {
  return window['go']['main']['App']['SignIn'](arg1);
}

export function SignInWithStellar(arg1) {
  return window['go']['main']['App']['SignInWithStellar'](arg1);
}

export function SignOut(arg1, arg2, arg3) {
  return window['go']['main']['App']['SignOut'](arg1, arg2, arg3);
}

export function SignUp(arg1) {
  return window['go']['main']['App']['SignUp'](arg1);
}

export function SynchronizeVault(arg1, arg2) {
  return window['go']['main']['App']['SynchronizeVault'](arg1, arg2);
}

export function TrashEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['TrashEntry'](arg1, arg2, arg3);
}

export function UpdateFolder(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateFolder'](arg1, arg2, arg3, arg4);
}

export function UploadToIPFS(arg1, arg2) {
  return window['go']['main']['App']['UploadToIPFS'](arg1, arg2);
}
